#ifndef	HOOKSHARESSE_VERSION_INCLUDED
#define HOOKSHARESSE_VERSION_INCLUDED

#define HOOKSHARESSE_VERSION_MAJOR		2
#define HOOKSHARESSE_VERSION_MINOR		0
#define HOOKSHARESSE_VERSION_PATCH		0
#define HOOKSHARESSE_VERSION_BETA		0
#define HOOKSHARESSE_VERSION_VERSTRING	"2, 0, 0, 0"

#endif
