#ifndef	HSHR_VERSION_INCLUDED
#define HSHR_VERSION_INCLUDED

#define MAKE_STR_HELPER(x) #x
#define MAKE_STR(x) MAKE_STR_HELPER(x)

#define HSHR_VERSION_MAJOR		4
#define HSHR_VERSION_MINOR		0
#define HSHR_VERSION_PATCH		0
#define HSHR_VERSION_BETA		0
#define HSHR_VERSION_VERSTRING	MAKE_STR(HSHR_VERSION_MAJOR) "." MAKE_STR(HSHR_VERSION_MINOR) "." MAKE_STR(HSHR_VERSION_PATCH) "." MAKE_STR(HSHR_VERSION_BETA)

#endif
