#ifndef	HOOKSHARESSE_VERSION_INCLUDED
#define HOOKSHARESSE_VERSION_INCLUDED

#define MAKE_STR_HELPER(x) #x
#define MAKE_STR(x) MAKE_STR_HELPER(x)

#define HOOKSHARESSE_VERSION_MAJOR		4
#define HOOKSHARESSE_VERSION_MINOR		0
#define HOOKSHARESSE_VERSION_PATCH		0
#define HOOKSHARESSE_VERSION_BETA		0
#define HOOKSHARESSE_VERSION_VERSTRING	MAKE_STR(HOOKSHARESSE_VERSION_MAJOR) "." MAKE_STR(HOOKSHARESSE_VERSION_MINOR) "." MAKE_STR(HOOKSHARESSE_VERSION_PATCH) "." MAKE_STR(HOOKSHARESSE_VERSION_BETA)

#endif
